### ISSUE TITLE
Permission not set to my user to create push project in repository

### ISSUE THREAD

**Issue by Pandurangv** [CbrainSolutions/E-PetrolPump#1]
![image](https://cloud.githubusercontent.com/assets/10114049/20861255/334740ba-b9b1-11e6-8fd3-80c10c1e0083.png)

**Comment by raksheshekhar1** [comment]
I have given you rights to push and pull.

**Comment by raksheshekhar1** [comment]
Let me know if you have any issue while pushing the code.
